version: 1

before:
  hooks:
    - go mod tidy

builds:
  - 
    main: ./cmd/godo/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"


release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: godo
    homepage: "https://github.com/ritikdhasmana/godo"
    repository:
      owner: ritikdhasmana
      name: homebrew-ritikd
    commit_author:
      name: ritik
      email: ritikdhasmana22@gmail.com

checksum:
  name_template: 'checksums.txt'
